"""expand_article_columns_to_text

Revision ID: 3cdf1cffd388
Revises: ca61c3937d6a
Create Date: 2026-09-16 11:28:16.417518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdf1cffd388'
down_revision: Union[str, None] = 'ca61c3937d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'volume',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='Journal publication volume',
               existing_nullable=True)
    op.alter_column('articles', 'issue',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='Journal publication issue',
               existing_nullable=True)
    op.alter_column('articles', 'pages',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='Article page range or article number',
               existing_nullable=True)
    op.alter_column('articles', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='Primary language of the publication',
               existing_nullable=True)
    op.alter_column('articles', 'oa_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='Open Access status indicator',
               existing_nullable=True)
    op.alter_column('articles', 'issn',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_comment='International Standard Serial Number',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'issn',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='International Standard Serial Number',
               existing_nullable=True)
    op.alter_column('articles', 'oa_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='Open Access status indicator',
               existing_nullable=True)
    op.alter_column('articles', 'language',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='Primary language of the publication',
               existing_nullable=True)
    op.alter_column('articles', 'pages',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='Article page range or article number',
               existing_nullable=True)
    op.alter_column('articles', 'issue',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='Journal publication issue',
               existing_nullable=True)
    op.alter_column('articles', 'volume',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_comment='Journal publication volume',
               existing_nullable=True)
    # ### end Alembic commands ###